defaults:
  - base_actor
  - _self_

_target_: verl_vla.workers.config.SFTActorConfig

ema:
  enable: false
  decay: 0.995

acp:
  enable: false
  indicator_dropout_prob: 0.0
  positive_tag: "Advantage: positive"
  negative_tag: "Advantage: negative"

mini_batch_size: 256
micro_batch_size: 32
